package groupna.projectNetflix.controllers;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import groupna.projectNetflix.entities.Artiste;
import groupna.projectNetflix.entities.Categorie;
import groupna.projectNetflix.entities.Episode;
import groupna.projectNetflix.entities.Film;
import groupna.projectNetflix.entities.Saison;
import groupna.projectNetflix.entities.Serie;

public class DataStore {
    private static List<Film> movies = new ArrayList<>();
    private static List<Serie> series = new ArrayList<>();

    static {
        movies = List.of(
            new Film(1,
               "A thief who steals corporate secrets through the use of dream-sharing technology.",
               List.of(Categorie.SCIENCE_FICTION, Categorie.ACTION),
               "Inception", LocalDate.of(2010, 7, 16),
               List.of(new Artiste(1, "Leonardo DiCaprio")),
               List.of(new Artiste(2, "Christopher Nolan")),
               "C:\\Users\\bouss\\Desktop\\netflix\\inception.jpg",
               LocalTime.of(2, 28), "C:\\Users\\bouss\\Desktop\\netflix\\Beast (2026) Movie Trailer.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\inception_tr.mp4"),
            
            new Film(2,
               "The lives of two mob hitmen, a boxer, and a gangster's wife intertwine.",
               List.of(Categorie.POLICIER, Categorie.DRAME),
               "Pulp Fiction", LocalDate.of(1994, 10, 14),
               List.of(new Artiste(3, "Samuel L. Jackson")),
               List.of(new Artiste(4, "Quentin Tarantino")),
               "C:\\Users\\bouss\\Desktop\\netflix\\pulp.jpg",
               LocalTime.of(2, 34), "C:\\Users\\bouss\\Desktop\\netflix\\pulp.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\pulp_tr.mp4"),

            new Film(3,
               "MMA legend Patton James is pulled back into the cage when his brother is in danger.",
               List.of(Categorie.ACTION, Categorie.DRAME),
               "Beast", LocalDate.of(2026, 4, 10),
               List.of(new Artiste(5, "Patton James")),
               List.of(new Artiste(6, "Xavier Grau")),
               "C:\\Users\\bouss\\Desktop\\netflix\\beast.jpg",
               LocalTime.of(1, 53), "C:\\Users\\bouss\\Desktop\\netflix\\Beast (2026) Movie Trailer.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\Beast (2026) Movie Trailer.mp4"),

            new Film(4,
               "A teenage hustler and a young man obsessed with alien abductions cross paths.",
               List.of(Categorie.DRAME, Categorie.MYSTERE, Categorie.THRILLER),
               "Mysterious Skin", LocalDate.of(2004, 9, 3),
               List.of(new Artiste(7, "Joseph Gordon-Levitt"), new Artiste(8, "Brady Corbet")),
               List.of(new Artiste(9, "Gregg Araki")),
               "C:\\Users\\bouss\\Desktop\\netflix\\mysterious_skin.jpg",
               LocalTime.of(1, 42), "C:\\Users\\bouss\\Desktop\\netflix\\mysterious_skin.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\mysterious_skin_tr.mp4"),

            new Film(5,
               "A troubled young boy risks everything to help a captive killer whale escape.",
               List.of(Categorie.FAMILLE, Categorie.AVENTURE),
               "Free Willy", LocalDate.of(1993, 7, 16),
               List.of(new Artiste(10, "Jason James Richter"), new Artiste(11, "Michael Madsen")),
               List.of(new Artiste(12, "Simon Wincer")),
               "C:\\Users\\bouss\\Desktop\\netflix\\free_willy.jpeg",
               LocalTime.of(1, 52), "C:\\Users\\bouss\\Desktop\\netflix\\free_willy.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\free_willy_tr.mp4"),

            new Film(6,
               "An elderly man reads to a woman with Alzheimer's the story of two young lovers.",
               List.of(Categorie.COMEDIE, Categorie.ROMANCE),
               "The Notebook", LocalDate.of(2004, 6, 25),
               List.of(new Artiste(13, "Ryan Gosling"), new Artiste(14, "Rachel McAdams")),
               List.of(new Artiste(15, "Nick Cassavetes")),
               "C:\\Users\\bouss\\Desktop\\netflix\\the_notebook.jpg",
               LocalTime.of(2, 3), "C:\\Users\\bouss\\Desktop\\netflix\\the_notebook.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\the_notebook_tr.mp4"),

            new Film(8,
               "A touching story where a girl's memories reset every night.",
               List.of(Categorie.ROMANCE, Categorie.DRAME),
               "Even If This Love Disappears (KR)", LocalDate.of(2024, 5, 10),
               List.of(new Artiste(19, "Kim Seon-ho"), new Artiste(20, "Go Youn-jung")),
               List.of(new Artiste(21, "Lee Jin-young")),
               "C:\\Users\\bouss\\Desktop\\netflix\\even if this love disappears from the world tonight.jpg",
               LocalTime.of(1, 58), "C:\\Users\\bouss\\Desktop\\netflix\\love_disappears_kr.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\love_disappears_kr_tr.mp4"),

            new Film(10,
               "At the age of 21, Tim discovers he can travel in time.",
               List.of(Categorie.ROMANCE, Categorie.COMEDIE, Categorie.FANTASY),
               "About Time", LocalDate.of(2013, 9, 4),
               List.of(new Artiste(25, "Domhnall Gleeson"), new Artiste(26, "Rachel McAdams"), new Artiste(27, "Bill Nighy")),
               List.of(new Artiste(28, "Richard Curtis")),
               "C:\\Users\\bouss\\Desktop\\netflix\\about_time.jpg",
               LocalTime.of(2, 3), "C:\\Users\\bouss\\Desktop\\netflix\\about_time.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\about_time_tr.mp4"),

            new Film(11,
               "On his fifth wedding anniversary, Nick Dunne reports that his wife has gone missing.",
               List.of(Categorie.THRILLER, Categorie.MYSTERE, Categorie.DRAME),
               "Gone Girl", LocalDate.of(2014, 10, 3),
               List.of(new Artiste(29, "Ben Affleck"), new Artiste(30, "Rosamund Pike"), new Artiste(31, "Neil Patrick Harris")),
               List.of(new Artiste(32, "David Fincher")),
               "C:\\Users\\bouss\\Desktop\\netflix\\gone_girl.jpg",
               LocalTime.of(2, 29), "C:\\Users\\bouss\\Desktop\\netflix\\gone_girl.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\gone_girl_tr.mp4"),

            new Film(13,
               "A high school girl finds herself untangling her feelings for a boy in her class.",
               List.of(Categorie.FAMILLE, Categorie.DRAME ,Categorie.ROMANCE),
               "Love Untangled", LocalDate.of(2025, 8, 29),
               List.of(new Artiste(36, "Shin Eun-soo")),
               List.of(new Artiste(38, "Netflix Director")),
               "C:\\Users\\bouss\\Desktop\\netflix\\love_untangled.jpg",
               LocalTime.of(1, 45), "C:\\Users\\bouss\\Desktop\\netflix\\love_untangled.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\love_untangled_tr.mp4"),

            new Film(14,
               "An advice columnist meets an advertising executive who bets he can make any woman fall in love.",
               List.of(Categorie.ROMANCE, Categorie.DRAME),
               "How to Lose a Guy in 10 Days", LocalDate.of(2003, 2, 7),
               List.of(new Artiste(39, "Kate Hudson"), new Artiste(40, "Matthew McConaughey")),
               List.of(new Artiste(41, "Donald Petrie")),
               "C:\\Users\\bouss\\Desktop\\netflix\\how to lose a guy in 10 days.jpg",
               LocalTime.of(1, 56), "C:\\Users\\bouss\\Desktop\\netflix\\how_to_lose.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\how_to_lose_tr.mp4"),

            new Film(15,
               "Elle Woods, a fashionable sorority queen, decides to follow her ex to Harvard Law School.",
               List.of(Categorie.COMEDIE, Categorie.ROMANCE),
               "Legally Blonde", LocalDate.of(2001, 7, 13),
               List.of(new Artiste(42, "Reese Witherspoon"), new Artiste(43, "Luke Wilson")),
               List.of(new Artiste(44, "Robert Luketic")),
               "C:\\Users\\bouss\\Desktop\\netflix\\legally_blonde.jpg",
               LocalTime.of(1, 36), "C:\\Users\\bouss\\Desktop\\netflix\\legally_blonde.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\legally_blonde_tr.mp4"),

            new Film(16,
               "To defeat his new girlfriend's seven evil exes, a garage-band bassist must fight through a series of high-octane video-game-style battles.",
               List.of(Categorie.ACTION, Categorie.COMEDIE, Categorie.ROMANCE),
               "Scott Pilgrim vs. the World",
               LocalDate.of(2010, 8, 13),
               List.of(new Artiste(45, "Michael Cera"), new Artiste(46, "Mary Elizabeth Winstead")),
               List.of(new Artiste(47, "Edgar Wright")),
               "C:\\Users\\bouss\\Desktop\\netflix\\scott_pilgrim.jpg",
               LocalTime.of(1, 52), "C:\\Users\\bouss\\Desktop\\netflix\\scott_pilgrim.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\scott_pilgrim_tr.mp4"),

            new Film(17,
               "A year after disposing of the body of a man they accidentally killed, a group of dumb teenagers are stalked by a bumbling serial killer.",
               List.of(Categorie.COMEDIE,Categorie.HORREUR),
               "Scary Movie",
               LocalDate.of(2000, 7, 7),
               List.of(new Artiste(48, "Anna Faris"), new Artiste(49, "Marlon Wayans"), new Artiste(50, "Regina Hall")),
               List.of(new Artiste(51, "Keenen Ivory Wayans")),
               "C:\\Users\\bouss\\Desktop\\netflix\\scary_movie.jpg",
               LocalTime.of(1, 28), "C:\\Users\\bouss\\Desktop\\netflix\\scary_movie.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\scary_movie_tr.mp4"),

            new Film(18,
               "A recently deceased couple tries to haunt the new inhabitants of their former home and recruits a loudmouthed ghost to help them.",
               List.of(Categorie.COMEDIE, Categorie.FANTASY,Categorie.HORREUR),
               "Beetlejuice",
               LocalDate.of(1988, 3, 30),
               List.of(new Artiste(52, "Michael Keaton"), new Artiste(53, "Winona Ryder"), new Artiste(54, "Catherine O'Hara")),
               List.of(new Artiste(55, "Tim Burton")),
               "C:\\Users\\bouss\\Desktop\\netflix\\beetlejuice.png",
               LocalTime.of(1, 32), "C:\\Users\\bouss\\Desktop\\netflix\\beetlejuice.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\beetlejuice_tr.mp4"),

            new Film(19,
               "An ambitious showman and visionary rises from nothing to create a mesmerizing spectacle that becomes a worldwide sensation.",
               List.of(Categorie.DRAME, Categorie.MUSICAL, Categorie.FAMILLE,Categorie.FANTASY),
               "The Greatest Showman",
               LocalDate.of(2017, 12, 20),
               List.of(new Artiste(56, "Hugh Jackman"), new Artiste(57, "Zac Efron"), new Artiste(58, "Zendaya")),
               List.of(new Artiste(59, "Michael Gracey")),
               "C:\\Users\\bouss\\Desktop\\netflix\\greatest_showman.png",
               LocalTime.of(1, 45), "C:\\Users\\bouss\\Desktop\\netflix\\greatest_showman.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\greatest_showman_tr.mp4"),

            new Film(20,
               "A young girl who loves reading discovers that all the library books she chooses have been previously checked out by the same mysterious boy.",
               List.of(Categorie.ANIMATION, Categorie.ANIME, Categorie.ROMANCE,Categorie.FAMILLE),
               "Whisper of the Heart",
               LocalDate.of(1995, 7, 15),
               List.of(new Artiste(60, "Yoko Honna"), new Artiste(61, "Issei Takahashi")),
               List.of(new Artiste(62, "Yoshifumi Kondo")),
               "C:\\Users\\bouss\\Desktop\\netflix\\whisper_of_the_heart.jpg",
               LocalTime.of(1, 51), "C:\\Users\\bouss\\Desktop\\netflix\\whisper_of_the_heart.mp4", "C:\\Users\\bouss\\Desktop\\netflix\\whisper_of_the_heart_tr.mp4"),

            new Film(21,
                "A retired pop singer turned actress's sense of reality is shattered as she is hounded by an obsessed fan and the ghosts of her past.",
                List.of(Categorie.ANIME, Categorie.THRILLER, Categorie.HORREUR),
                "Perfect Blue",
                LocalDate.of(1997, 8, 5),
                List.of(new Artiste(63, "Junko Iwao"), new Artiste(64, "Rica Matsumoto")),
                List.of(new Artiste(65, "Satoshi Kon")),
                "C:\\Users\\bouss\\Desktop\\netflix\\perfect_blue.jpg",
                LocalTime.of(1, 21),
                "C:\\Users\\bouss\\Desktop\\netflix\\perfect_blue.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\perfect_blue_tr.mp4"),

            new Film(22,
                "A mild-mannered businessman travels from Denver to Miami to confront the deceptively harmless-looking woman who has lived it up after stealing his identity.",
                List.of(Categorie.COMEDIE, Categorie.ACTION, Categorie.POLICIER),
                "Identity Thief",
                LocalDate.of(2013, 2, 8),
                List.of(new Artiste(66, "Jason Bateman"), new Artiste(67, "Melissa McCarthy")),
                List.of(new Artiste(68, "Seth Gordon")),
                "C:\\Users\\bouss\\Desktop\\netflix\\identity_thief.jpg",
                LocalTime.of(1, 51),
                "C:\\Users\\bouss\\Desktop\\netflix\\identity_thief.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\identity_thief_tr.mp4"),

            new Film(23,
                "Four siblings play hide-and-seek and find a wardrobe that transports them to a magical world once peaceful but now frozen in eternal winter.",
                List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.FANTASY, Categorie.FAMILLE),
                "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
                LocalDate.of(2005, 12, 9),
                List.of(new Artiste(69, "Georgie Henley"), new Artiste(70, "Skandar Keynes"), new Artiste(71, "Tilda Swinton")),
                List.of(new Artiste(72, "Andrew Adamson")),
                "C:\\Users\\bouss\\Desktop\\netflix\\narnia.jpg",
                LocalTime.of(2, 23),
                "C:\\Users\\bouss\\Desktop\\netflix\\narnia.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\narnia_tr.mp4"),

            new Film(24,
                "A young boy known as the Avatar must master the four elemental powers to save the world from the ruthless Fire Nation and restore balance.",
                List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.FANTASY),
                "The Last Airbender",
                LocalDate.of(2010, 7, 1),
                List.of(new Artiste(73, "Noah Ringer"), new Artiste(74, "Dev Patel"), new Artiste(75, "Nicola Peltz")),
                List.of(new Artiste(76, "M. Night Shyamalan")),
                "C:\\Users\\bouss\\Desktop\\netflix\\last_airbender.jpg",
                LocalTime.of(1, 43),
                "C:\\Users\\bouss\\Desktop\\netflix\\last_airbender.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\last_airbender_tr.mp4"),

            new Film(25,
                "When two kids find and play a magical board game, they release a man trapped in it for decades and a host of dangers that can only be stopped by finishing the game.",
                List.of(Categorie.AVENTURE, Categorie.COMEDIE, Categorie.FANTASY),
                "Jumanji",
                LocalDate.of(1995, 12, 15),
                List.of(new Artiste(77, "Robin Williams"), new Artiste(78, "Kirsten Dunst"), new Artiste(79, "Bonnie Hunt")),
                List.of(new Artiste(80, "Joe Johnston")),
                "C:\\Users\\bouss\\Desktop\\netflix\\jumanji.jpg",
                LocalTime.of(1, 44),
                "C:\\Users\\bouss\\Desktop\\netflix\\jumanji.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\jumanji_tr.mp4"),

            new Film(26,
                "A detective investigates the death of a patriarch of an eccentric, combative family.",
                List.of(Categorie.MYSTERE, Categorie.COMEDIE, Categorie.DRAME),
                "Knives Out",
                LocalDate.of(2019, 11, 27),
                List.of(new Artiste(81, "Daniel Craig"), new Artiste(82, "Ana de Armas"), new Artiste(83, "Chris Evans")),
                List.of(new Artiste(84, "Rian Johnson")),
                "C:\\Users\\bouss\\Desktop\\netflix\\knives_out.jpg",
                LocalTime.of(2, 10),
                "C:\\Users\\bouss\\Desktop\\netflix\\knives_out.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\knives_out_tr.mp4"),

            new Film(27,
                "When Patrizia Reggiani, an outsider from humble beginnings, marries into the Gucci family, her unbridled ambition begins to unravel their legacy and triggers a reckless spiral of betrayal, decadence, revenge, and ultimately murder.",
                List.of(Categorie.POLICIER),
                "House of Gucci",
                LocalDate.of(2021, 11, 24),
                List.of(new Artiste(89, "Lady Gaga"), new Artiste(90, "Adam Driver"), new Artiste(91, "Al Pacino")),
                List.of(new Artiste(92, "Ridley Scott")),
                "C:\\Users\\bouss\\Desktop\\netflix\\house_of_gucci.jpg",
                LocalTime.of(2, 38),
                "C:\\Users\\bouss\\Desktop\\netflix\\house_of_gucci.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\house_of_gucci_tr.mp4"),

            new Film(28,
                "A New York City cop and his wife go on a European vacation to reinvigorate the spark in their marriage, only to end up being framed and on the run for the death of an elderly billionaire.",
                List.of(Categorie.COMEDIE, Categorie.POLICIER, Categorie.ACTION),
                "Murder Mystery",
                LocalDate.of(2019, 6, 14),
                List.of(new Artiste(93, "Adam Sandler"), new Artiste(94, "Jennifer Aniston")),
                List.of(new Artiste(95, "Kyle Newacheck")),
                "C:\\Users\\bouss\\Desktop\\netflix\\murder_mystery.jpg",
                LocalTime.of(1, 37),
                "C:\\Users\\bouss\\Desktop\\netflix\\murder_mystery.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\murder_mystery_tr.mp4"),

            new Film(29,
                "A former assassin, known as The Bride, awakens from a four-year coma and embarks on a quest for revenge against the team of killers who betrayed her.",
                List.of(Categorie.ACTION),
                "Kill Bill: Vol. 1",
                LocalDate.of(2003, 10, 10),
                List.of(new Artiste(96, "Uma Thurman"), new Artiste(97, "Lucy Liu"), new Artiste(98, "Vivica A. Fox")),
                List.of(new Artiste(99, "Quentin Tarantino")),
                "C:\\Users\\bouss\\Desktop\\netflix\\kill_bill.jpg",
                LocalTime.of(1, 51),
                "C:\\Users\\bouss\\Desktop\\netflix\\kill_bill.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\kill_bill_tr.mp4"),

            new Film(30,
                "When a machine that allows therapists to enter their patients' dreams is stolen, all hell breaks loose, and only a young female therapist named Paprika can stop it.",
                List.of(Categorie.ANIME, Categorie.FANTASY, Categorie.THRILLER),
                "Paprika",
                LocalDate.of(2006, 11, 25),
                List.of(new Artiste(100, "Megumi Hayashibara"), new Artiste(101, "Toru Furuya")),
                List.of(new Artiste(102, "Satoshi Kon")),
                "C:\\Users\\bouss\\Desktop\\netflix\\paprika.jpg",
                LocalTime.of(1, 30),
                "C:\\Users\\bouss\\Desktop\\netflix\\paprika.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\paprika_tr.mp4"),

            new Film(31,
                "A young bride's wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game of hide-and-seek.",
                List.of(Categorie.COMEDIE, Categorie.HORREUR, Categorie.THRILLER),
                "Ready or Not",
                LocalDate.of(2019, 8, 21),
                List.of(new Artiste(103, "Samara Weaving"), new Artiste(104, "Adam Brody"), new Artiste(105, "Mark O'Brien")),
                List.of(new Artiste(106, "Matt Bettinelli-Olpin"), new Artiste(107, "Tyler Gillett")),
                "C:\\Users\\bouss\\Desktop\\netflix\\ready_or_not.jpg",
                LocalTime.of(1, 35),
                "C:\\Users\\bouss\\Desktop\\netflix\\ready_or_not.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\ready_or_not_tr.mp4"),

            new Film(32,
                "Two strangers awaken in a room with no recollection of how they got there, and soon discover they are pawns in a deadly game perpetrated by a notorious serial killer.",
                List.of(Categorie.HORREUR, Categorie.THRILLER),
                "Saw",
                LocalDate.of(2004, 10, 29),
                List.of(new Artiste(108, "Cary Elwes"), new Artiste(109, "Leigh Whannell"), new Artiste(110, "Tobin Bell")),
                List.of(new Artiste(111, "James Wan")),
                "C:\\Users\\bouss\\Desktop\\netflix\\saw.jpg",
                LocalTime.of(1, 43),
                "C:\\Users\\bouss\\Desktop\\netflix\\saw.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\saw_tr.mp4"),

            new Film(33,
                "An intimate look at the life and legacy of martial arts icon Bruce Lee, exploring his struggles with identity, racism, and his rise to global superstardom.",
                List.of(Categorie.DOCUMENTAIRE),
                "Be Water",
                LocalDate.of(2020, 6, 7),
                List.of(new Artiste(112, "Bruce Lee"), new Artiste(113, "Linda Lee Cadwell")),
                List.of(new Artiste(114, "Bao Nguyen")),
                "C:\\Users\\bouss\\Desktop\\netflix\\be_water.jpg",
                LocalTime.of(1, 36),
                "C:\\Users\\bouss\\Desktop\\netflix\\be_water.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\be_water_tr.mp4"),

            new Film(34,
                "An intimate look at the life of Lady Gaga as she records a new album, prepares for her Super Bowl halftime show, and deals with personal struggles.",
                List.of(Categorie.DOCUMENTAIRE, Categorie.MUSICAL),
                "Gaga: Five Foot Two",
                LocalDate.of(2017, 9, 22),
                List.of(new Artiste(89, "Lady Gaga")),
                List.of(new Artiste(115, "Chris Moukarbel")),
                "C:\\Users\\bouss\\Desktop\\netflix\\gaga_five_foot_two.jpg",
                LocalTime.of(1, 40),
                "C:\\Users\\bouss\\Desktop\\netflix\\gaga_five_foot_two.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\gaga_five_foot_two_tr.mp4"),

            new Film(35,
                "In her own words, through personal videos and diaries, Pamela Anderson shares the story of her rise to fame, rocky romances and infamous sex tape scandal.",
                List.of(Categorie.DOCUMENTAIRE),
                "Pamela, a Love Story",
                LocalDate.of(2023, 1, 31),
                List.of(new Artiste(116, "Pamela Anderson")),
                List.of(new Artiste(117, "Ryan White")),
                "C:\\Users\\bouss\\Desktop\\netflix\\pamela_a_love_story.jpg",
                LocalTime.of(1, 52),
                "C:\\Users\\bouss\\Desktop\\netflix\\pamela_a_love_story.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\pamela_a_love_story_tr.mp4"),

            new Film(36,
                "Using raw, firsthand footage, this documentary examines the disappearance of Shanann Watts and her children, and the terrible events that followed.",
                List.of(Categorie.DOCUMENTAIRE, Categorie.MYSTERE),
                "American Murder: The Family Next Door",
                LocalDate.of(2020, 9, 30),
                List.of(new Artiste(118, "Shanann Watts"), new Artiste(119, "Chris Watts")),
                List.of(new Artiste(120, "Jenny Popplewell")),
                "C:\\Users\\bouss\\Desktop\\netflix\\american_murder.jpg",
                LocalTime.of(1, 22),
                "C:\\Users\\bouss\\Desktop\\netflix\\american_murder.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\american_murder_tr.mp4"),

            new Film(37,
                "Olivia Rodrigo takes a familiar road trip from Salt Lake City to Los Angeles, reflecting on the writing and creating of her debut album 'SOUR' and performing new arrangements of her songs.",
                List.of(Categorie.DOCUMENTAIRE, Categorie.MUSICAL),
                "Olivia Rodrigo: driving home 2 u (a SOUR film)",
                LocalDate.of(2022, 3, 25),
                List.of(new Artiste(121, "Olivia Rodrigo"), new Artiste(122, "Jacob Collier")),
                List.of(new Artiste(123, "Stacey Lee")),
                "C:\\Users\\bouss\\Desktop\\netflix\\driving_home_2_u.jpg",
                LocalTime.of(1, 16),
                "C:\\Users\\bouss\\Desktop\\netflix\\driving_home_2_u.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\driving_home_2_u_tr.mp4"),

            new Film(38,
                "An obsessed scientist assembles a living being from parts of exhumed corpses, only to face tragic consequences when the creature is rejected by society.",
                List.of(Categorie.HORREUR, Categorie.SCIENCE_FICTION, Categorie.DRAME),
                "Frankenstein",
                LocalDate.of(1931, 11, 21),
                List.of(new Artiste(124, "Colin Clive"), new Artiste(125, "Boris Karloff"), new Artiste(126, "Mae Clarke")),
                List.of(new Artiste(127, "James Whale")),
                "C:\\Users\\bouss\\Desktop\\netflix\\frankenstein.jpg",
                LocalTime.of(1, 10),
                "C:\\Users\\bouss\\Desktop\\netflix\\frankenstein.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\frankenstein_tr.mp4"),

            new Film(40,
                "Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow 'runners' for a shot at escape.",
                List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.SCIENCE_FICTION),
                "The Maze Runner",
                LocalDate.of(2014, 9, 19),
                List.of(new Artiste(136, "Dylan O'Brien"), new Artiste(137, "Kaya Scodelario"), new Artiste(138, "Thomas Brodie-Sangster")),
                List.of(new Artiste(139, "Wes Ball")),
                "C:\\Users\\bouss\\Desktop\\netflix\\maze_runner.jpg",
                LocalTime.of(1, 53),
                "C:\\Users\\bouss\\Desktop\\netflix\\maze_runner.mp4",
                "C:\\Users\\bouss\\Desktop\\netflix\\maze_runner_tr.mp4"),
            new Film(41,
                    "In the distant future, a small waste-collecting robot embarks on a space journey that will ultimately decide the fate of mankind.",
                    List.of(Categorie.ANIMATION, Categorie.AVENTURE, Categorie.SCIENCE_FICTION),
                    "WALL-E",
                    LocalDate.of(2008, 6, 27),
                    List.of(new Artiste(140, "Ben Burtt"), new Artiste(141, "Elissa Knight"), new Artiste(142, "Jeff Garlin")),
                    List.of(new Artiste(143, "Andrew Stanton")),
                    "C:\\Users\\bouss\\Desktop\\netflix\\wall_e.jpg",
                    LocalTime.of(1, 38),
                    "C:\\Users\\bouss\\Desktop\\netflix\\wall_e.mp4",
                    "C:\\Users\\bouss\\Desktop\\netflix\\wall_e_tr.mp4"),

                new Film(42,
                    "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
                    List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.SCIENCE_FICTION),
                    "Dune",
                    LocalDate.of(2021, 10, 22),
                    List.of(new Artiste(144, "Timothée Chalamet"), new Artiste(145, "Rebecca Ferguson"), new Artiste(146, "Oscar Isaac")),
                    List.of(new Artiste(147, "Denis Villeneuve")),
                    "C:\\Users\\bouss\\Desktop\\netflix\\dune.jpg",
                    LocalTime.of(2, 35),
                    "C:\\Users\\bouss\\Desktop\\netflix\\dune.mp4",
                    "C:\\Users\\bouss\\Desktop\\netflix\\dune_tr.mp4"),

                new Film(43,
                    "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
                    List.of(Categorie.ACTION, Categorie.SCIENCE_FICTION, Categorie.THRILLER),
                    "Blade Runner",
                    LocalDate.of(1982, 6, 25),
                    List.of(new Artiste(148, "Harrison Ford"), new Artiste(149, "Rutger Hauer"), new Artiste(150, "Sean Young")),
                    List.of(new Artiste(151, "Ridley Scott")),
                    "C:\\Users\\bouss\\Desktop\\netflix\\blade_runner.jpg",
                    LocalTime.of(1, 57),
                    "C:\\Users\\bouss\\Desktop\\netflix\\blade_runner.mp4",
                    "C:\\Users\\bouss\\Desktop\\netflix\\blade_runner_tr.mp4"),

                new Film(44,
                    "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station.",
                    List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.SCIENCE_FICTION),
                    "Star Wars: Episode IV - A New Hope",
                    LocalDate.of(1977, 5, 25),
                    List.of(new Artiste(152, "Mark Hamill"), new Artiste(153, "Harrison Ford"), new Artiste(154, "Carrie Fisher")),
                    List.of(new Artiste(155, "George Lucas")),
                    "C:\\Users\\bouss\\Desktop\\netflix\\star_wars.jpg",
                    LocalTime.of(2, 1),
                    "C:\\Users\\bouss\\Desktop\\netflix\\star_wars.mp4",
                    "C:\\Users\\bouss\\Desktop\\netflix\\star_wars_tr.mp4"),
                
                new Film(45,
                	    "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.",
                	    List.of(Categorie.ANIMATION, Categorie.AVENTURE, Categorie.COMEDIE),
                	    "Ratatouille",
                	    LocalDate.of(2007, 6, 29),
                	    List.of(new Artiste(156, "Patton Oswalt"), new Artiste(157, "Ian Holm"), new Artiste(158, "Lou Romano")),
                	    List.of(new Artiste(159, "Brad Bird")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\ratatouille.jpeg",
                	    LocalTime.of(1, 51),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\ratatouille.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\ratatouille_tr.mp4"),

                	new Film(46,
                	    "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
                	    List.of(Categorie.ANIMATION, Categorie.AVENTURE, Categorie.MUSICAL, Categorie.FAMILLE),
                	    "Coco",
                	    LocalDate.of(2017, 11, 22),
                	    List.of(new Artiste(160, "Anthony Gonzalez"), new Artiste(161, "Gael García Bernal"), new Artiste(162, "Benjamin Bratt")),
                	    List.of(new Artiste(163, "Lee Unkrich")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco.jpeg",
                	    LocalTime.of(1, 45),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco_tr.mp4"),

                	new Film(47,
                	    "When a litter of Dalmatian puppies is abducted by the minions of Cruella de Vil, the parents must find them before she uses them for a diabolical fashion statement.",
                	    List.of(Categorie.ANIMATION, Categorie.AVENTURE, Categorie.FAMILLE),
                	    "One Hundred and One Dalmatians",
                	    LocalDate.of(1961, 1, 25),
                	    List.of(new Artiste(164, "Rod Taylor"), new Artiste(165, "Betty Lou Gerson"), new Artiste(166, "Cate Bauer")),
                	    List.of(new Artiste(167, "Clyde Geronimi"), new Artiste(168, "Hamilton Luske")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\101_dalmatians.jpeg",
                	    LocalTime.of(1, 19),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\101_dalmatians.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\101_dalmatians_tr.mp4"),

                	new Film(48,
                	    "Lady, a pampered cocker spaniel, and Tramp, a freewheeling mutt with a heart of gold, embark on an unexpected adventure and fall in love despite their different backgrounds.",
                	    List.of(Categorie.ANIMATION, Categorie.AVENTURE, Categorie.ROMANCE),
                	    "Lady and the Tramp",
                	    LocalDate.of(1955, 6, 22),
                	    List.of(new Artiste(169, "Barbara Luddy"), new Artiste(170, "Larry Roberts"), new Artiste(171, "Peggy Lee")),
                	    List.of(new Artiste(167, "Clyde Geronimi"), new Artiste(168, "Hamilton Luske"), new Artiste(172, "Wilfred Jackson")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\lady_and_the_tramp.jpg",
                	    LocalTime.of(1, 16),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\lady_and_the_tramp.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\lady_and_the_tramp_tr.mp4"),

                	new Film(49,
                	    "While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.",
                	    List.of(Categorie.ANIMATION, Categorie.ACTION, Categorie.AVENTURE, Categorie.SCIENCE_FICTION),
                	    "The Incredibles",
                	    LocalDate.of(2004, 11, 5),
                	    List.of(new Artiste(173, "Craig T. Nelson"), new Artiste(174, "Holly Hunter"), new Artiste(175, "Samuel L. Jackson")),
                	    List.of(new Artiste(159, "Brad Bird")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\the_incredibles.jpg",
                	    LocalTime.of(1, 55),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\the_incredibles.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\the_incredibles_tr.mp4"),

                	new Film(50,
                	    "In 1800s England, a well-meaning but selfish young woman meddles in the love lives of her friends.",
                	    List.of(Categorie.COMEDIE, Categorie.DRAME, Categorie.HISTORIQUE),
                	    "Emma.",
                	    LocalDate.of(2020, 2, 21),
                	    List.of(new Artiste(176, "Anya Taylor-Joy"), new Artiste(177, "Johnny Flynn"), new Artiste(178, "Josh O'Connor")),
                	    List.of(new Artiste(179, "Autumn de Wilde")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\emma.jpg",
                	    LocalTime.of(2, 4),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\emma.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\emma_tr.mp4"),

                	new Film(51,
                	    "Vampire Count Orlok expresses interest in a new residence and real estate agent Hutter's wife.",
                	    List.of(Categorie.HORREUR, Categorie.FANTASY, Categorie.HISTORIQUE),
                	    "Nosferatu",
                	    LocalDate.of(1922, 3, 4),
                	    List.of(new Artiste(180, "Max Schreck"), new Artiste(181, "Gustav von Wangenheim"), new Artiste(182, "Greta Schröder")),
                	    List.of(new Artiste(183, "F.W. Murnau")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\nosferatu.jpg",
                	    LocalTime.of(1, 34),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\nosferatu.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\nosferatu_tr.mp4"),

                	new Film(52,
                	    "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.",
                	    List.of(Categorie.DRAME, Categorie.HISTORIQUE),
                	    "Little Women",
                	    LocalDate.of(2019, 12, 25),
                	    List.of(new Artiste(211, "Saoirse Ronan"), new Artiste(212, "Emma Watson"), new Artiste(213, "Florence Pugh")),
                	    List.of(new Artiste(214, "Greta Gerwig")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\little_women.jpeg",
                	    LocalTime.of(2, 15),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\little_women.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\little_women_tr.mp4"),

                	new Film(53,
                	    "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class.",
                	    List.of(Categorie.DRAME, Categorie.ROMANCE, Categorie.HISTORIQUE),
                	    "Pride & Prejudice",
                	    LocalDate.of(2005, 9, 16),
                	    List.of(new Artiste(188, "Keira Knightley"), new Artiste(189, "Matthew Macfadyen"), new Artiste(190, "Rosamund Pike")),
                	    List.of(new Artiste(191, "Joe Wright")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\pride_and_prejudice.jpg",
                	    LocalTime.of(2, 9),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\pride_and_prejudice.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\pride_and_prejudice_tr.mp4"),

                	new Film(54,
                	    "Jean Valjean, a former convict who has built a new life for himself, is pursued for decades by the obsessive Inspector Javert, while caught up in the beginnings of the French Revolution.",
                	    List.of(Categorie.DRAME, Categorie.POLICIER, Categorie.HISTORIQUE),
                	    "Les Misérables",
                	    LocalDate.of(1998, 5, 1),
                	    List.of(new Artiste(196, "Liam Neeson"), new Artiste(197, "Geoffrey Rush"), new Artiste(198, "Uma Thurman")),
                	    List.of(new Artiste(199, "Bille August")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\les_miserables_1998.jpg",
                	    LocalTime.of(2, 14),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\les_miserables_1998.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\les_miserables_1998_tr.mp4"),

                	new Film(55,
                	    "The story of Gabrielle 'Coco' Chanel, who began her life as a headstrong orphan and, through an extraordinary journey, became the legendary couturier who embodied the modern woman.",
                	    List.of(Categorie.DRAME, Categorie.BIOPIC),
                	    "Coco Before Chanel",
                	    LocalDate.of(2009, 4, 22),
                	    List.of(new Artiste(207, "Audrey Tautou"), new Artiste(208, "Benoît Poelvoorde"), new Artiste(209, "Alessandro Nivola")),
                	    List.of(new Artiste(210, "Anne Fontaine")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco_before_chanel.jpg",
                	    LocalTime.of(1, 50),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco_before_chanel.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\coco_before_chanel_tr.mp4"),

                	new Film(56,
                	    "A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral.",
                	    List.of(Categorie.DRAME, Categorie.MUSICAL, Categorie.ROMANCE),
                	    "A Star Is Born",
                	    LocalDate.of(2018, 10, 5),
                	    List.of(new Artiste(204, "Lady Gaga"), new Artiste(205, "Bradley Cooper"), new Artiste(206, "Sam Elliott")),
                	    List.of(new Artiste(205, "Bradley Cooper")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\a_star_is_born.jpg",
                	    LocalTime.of(2, 16),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\a_star_is_born.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\a_star_is_born_tr.mp4"),

                	new Film(62,
                	    "In an abandoned Tokyo overrun by bubbles and gravitational abnormalities, a gifted young man meets a mysterious girl who changes his life forever.",
                	    List.of(Categorie.ANIME, Categorie.ACTION, Categorie.AVENTURE, Categorie.FAMILLE),
                	    "Bubble",
                	    LocalDate.of(2022, 4, 28),
                	    List.of(new Artiste(215, "Jun Shison"), new Artiste(216, "Riria"), new Artiste(217, "Mamoru Miyano")),
                	    List.of(new Artiste(218, "Tetsurô Araki")),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\bubble.jpg",
                	    LocalTime.of(1, 40),
                	    "C:\\Users\\bouss\\Desktop\\netflix\\bubble.mp4",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\bubble_tr.mp4")
            );

                	// --- SEASONS & SERIES ---
                	Map<Saison, List<Episode>> bbSaisons = new HashMap<>();
                	List<Episode> s1Episodes = new ArrayList<>();
                	Saison s1 = new Saison(1, 1, LocalDate.of(2008, 1, 20), "Season 1", "Walter White starts cooking.", "C:\\Users\\bouss\\Desktop\\netflix\\bb_s1.mp4");

                	s1Episodes.add(new Episode(1, 101, "Pilot episode.", "Pilot", LocalTime.of(0, 58), "C:\\Users\\bouss\\Desktop\\netflix\\Beast (2026) Movie Trailer.mp4"));
                	Episode ep = new Episode(2, 101, "Pilot episode.", "Pilot", LocalTime.of(0, 58), "C:\\Users\\bouss\\Desktop\\netflix\\Beast (2026) Movie Trailer.mp4");
                	s1Episodes.add(ep);
                	bbSaisons.put(s1, s1Episodes);

                	Map<Saison, List<Episode>> fpSaisons = new HashMap<>();
                	Saison fpS1 = new Saison(2, 1, LocalDate.of(2023, 5, 31), "Season 1", "Camila creates a sexy profile.", "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1.mp4");
                	fpSaisons.put(fpS1, new ArrayList<>());

                	// --- SEASON 1 ---
                	List<Episode> fpS1Episodes = new ArrayList<>();
                	fpS1Episodes.add(new Episode(1, 1, "Camila meets her Prince Charming through a dating app.", "The Illusion", LocalTime.of(0, 45), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e1.mp4"));
                	fpS1Episodes.add(new Episode(2, 2, "Camila discovers Fernando is not who he says he is.", "Shadows", LocalTime.of(0, 47), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e2.mp4"));
                	fpS1Episodes.add(new Episode(3, 3, "Determined to find the truth, Camila begins her own investigation.", "The Trap", LocalTime.of(0, 42), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e3.mp4"));
                	fpS1Episodes.add(new Episode(4, 4, "A mysterious figure from Fernando's past appears.", "The Secret", LocalTime.of(0, 50), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e4.mp4"));
                	fpS1Episodes.add(new Episode(5, 5, "Camila realizes the danger she has put herself in.", "No Way Out", LocalTime.of(0, 48), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e5.mp4"));
                	fpS1Episodes.add(new Episode(6, 6, "Tensions rise as the lies become harder to maintain.", "Broken Trust", LocalTime.of(0, 45), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e6.mp4"));
                	fpS1Episodes.add(new Episode(7, 7, "A shocking revelation changes everything for Camila.", "The Reveal", LocalTime.of(0, 52), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e7.mp4"));
                	fpS1Episodes.add(new Episode(8, 8, "The true identity of the man behind the profile is found.", "Masks Off", LocalTime.of(0, 44), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e8.mp4"));
                	fpS1Episodes.add(new Episode(9, 9, "Camila plans her escape from the web of deceit.", "The Escape", LocalTime.of(0, 49), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e9.mp4"));
                	fpS1Episodes.add(new Episode(10, 10, "The final confrontation leads to a deadly conclusion.", "The End", LocalTime.of(0, 55), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s1_e10.mp4"));
                	fpSaisons.put(fpS1, fpS1Episodes);

                	// --- SEASON 2 ---
                	List<Episode> fpS2Episodes = new ArrayList<>();
                	Saison fpS2 = new Saison(3, 2, LocalDate.of(2024, 6, 15), "Season 2", "The web of lies expands.", "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2.mp4");
                	fpS2Episodes.add(new Episode(11, 1, "Camila tries to restart her life but her past follows her.", "New Life", LocalTime.of(0, 50), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e1.mp4"));
                	fpS2Episodes.add(new Episode(12, 2, "A new profile emerges that looks eerily familiar.", "Double Trouble", LocalTime.of(0, 48), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e2.mp4"));
                	fpS2Episodes.add(new Episode(13, 3, "Old enemies return to settle their scores.", "Vendetta", LocalTime.of(0, 51), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e3.mp4"));
                	fpS2Episodes.add(new Episode(14, 4, "Camila finds an unexpected ally in her fight for the truth.", "Allies", LocalTime.of(0, 46), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e4.mp4"));
                	fpS2Episodes.add(new Episode(15, 5, "A high-stakes game of cat and mouse begins.", "The Game", LocalTime.of(0, 53), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e5.mp4"));
                	fpS2Episodes.add(new Episode(16, 6, "Secrets from the first season come back to haunt everyone.", "Haunted", LocalTime.of(0, 44), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e6.mp4"));
                	fpS2Episodes.add(new Episode(17, 7, "A betrayal from within the circle threatens everything.", "Betrayal", LocalTime.of(0, 47), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e7.mp4"));
                	fpS2Episodes.add(new Episode(18, 8, "The truth about the dating app company is uncovered.", "The Network", LocalTime.of(0, 50), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e8.mp4"));
                	fpS2Episodes.add(new Episode(19, 9, "Camila must make a sacrifice to protect those she loves.", "Sacrifice", LocalTime.of(0, 52), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e9.mp4"));
                	fpS2Episodes.add(new Episode(20, 10, "The final showdown leaves no one untouched.", "Final Justice", LocalTime.of(1, 00), "C:\\Users\\bouss\\Desktop\\netflix\\fp_s2_e10.mp4"));
                	fpSaisons.put(fpS2, fpS2Episodes);

                	// --- What Comes After Love ---
                	Map<Saison, List<Episode>> wcalSaisons = new HashMap<>();
                	List<Episode> wcalS1Episodes = new ArrayList<>();
                	Saison wcalS1 = new Saison(
                	    4,
                	    1,
                	    LocalDate.of(2024, 9, 27),
                	    "Season 1",
                	    "Five years after a heartbreaking breakup in Japan, Hong and Jung-go meet again in Korea.",
                	    "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1.mp4"
                	);

                	wcalS1Episodes.add(new Episode(1, 1, "Hong arrives in Japan for study and meets the charming Jung-go.", "First Encounter", LocalTime.of(0, 55), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e1.mp4"));
                    wcalS1Episodes.add(new Episode(2, 2, "The couple shares a beautiful spring together in Tokyo.", "Spring in Tokyo", LocalTime.of(0, 52), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e2.mp4"));
                    wcalS1Episodes.add(new Episode(3, 3, "Misunderstandings begin to tear their young love apart.", "Fading Memories", LocalTime.of(0, 50), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e3.mp4"));
                    wcalS1Episodes.add(new Episode(4, 4, "Five years later, Hong is shocked to see Jung-go at her workplace.", "The Reunion", LocalTime.of(0, 58), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e4.mp4"));
                    wcalS1Episodes.add(new Episode(5, 5, "Hong struggles with the pain of the past while Jung-go tries to apologize.", "Words Unspoken", LocalTime.of(0, 54), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e5.mp4"));
                    wcalS1Episodes.add(new Episode(6, 6, "Can love truly survive five years of silence?", "The Final Choice", LocalTime.of(1, 05), "C:\\Users\\bouss\\Desktop\\netflix\\wcal_s1_e6.mp4"));

                    wcalSaisons.put(wcalS1, wcalS1Episodes);
                    
                    Map<Saison, List<Episode>> cnSaisons = new HashMap<>();
                 // --- CASTLEVANIA: NOCTURNE SEASON 1 ---
                    List<Episode> cnS1Episodes = new ArrayList<>();
                    Saison cnS1 = new Saison(1, 1, LocalDate.of(2023, 9, 28), "Season 1", "In the midst of the French Revolution, Richter Belmont fights to stop a vampire messiah.", "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1.mp4");

                    cnS1Episodes.add(new Episode(1, 1, "Richter meets Maria Renard and faces the night creatures in Machecoul.", "A Common Enemy", LocalTime.of(0, 35), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e1.mp4"));
                    cnS1Episodes.add(new Episode(2, 2, "The depth of the vampire conspiracy within the Church begins to surface.", "Say the Word", LocalTime.of(0, 29), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e2.mp4"));
                    cnS1Episodes.add(new Episode(3, 3, "Abbot Emanuel reveals his dark methods for protecting his flock.", "The Night Creatures", LocalTime.of(0, 27), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e3.mp4"));
                    cnS1Episodes.add(new Episode(4, 4, "Annette and Edouard's past in Saint-Domingue is revealed.", "Horror of the Deep", LocalTime.of(0, 28), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e4.mp4"));
                    cnS1Episodes.add(new Episode(5, 5, "Richter is forced to confront the vampire who killed his mother.", "Natural Order", LocalTime.of(0, 25), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e5.mp4"));
                    cnS1Episodes.add(new Episode(6, 6, "The group attempts to destroy the machine creating the night creatures.", "The Guilty Party", LocalTime.of(0, 26), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e6.mp4"));
                    cnS1Episodes.add(new Episode(7, 7, "Erzsebet Báthory demonstrates her terrifying, god-like power.", "She Is the Sun", LocalTime.of(0, 28), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e7.mp4"));
                    cnS1Episodes.add(new Episode(8, 8, "A legendary vampire hunter arrives just as hope seems lost.", "Devourer of Light", LocalTime.of(0, 30), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s1_e8.mp4"));

                    cnSaisons.put(cnS1, cnS1Episodes);

                    // --- CASTLEVANIA: NOCTURNE SEASON 2 ---
                    List<Episode> cnS2Episodes = new ArrayList<>();
                    Saison cnS2 = new Saison(2, 2, LocalDate.of(2025, 1, 16), "Season 2", "With Alucard at their side, the hunters wage a final war against the Devourer of Light.", "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2.mp4");

                    cnS2Episodes.add(new Episode(9, 1, "Alucard joins the fray, bringing knowledge of the ancient war.", "The Prince's Return", LocalTime.of(0, 32), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e1.mp4"));
                    cnS2Episodes.add(new Episode(10, 2, "Richter and Alucard strike an uneasy but powerful alliance.", "Old Blood, New Steel", LocalTime.of(0, 30), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e2.mp4"));
                    cnS2Episodes.add(new Episode(11, 3, "Maria's magical lineage is tested as the eclipse draws near.", "The Speaker's Legacy", LocalTime.of(0, 29), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e3.mp4"));
                    cnS2Episodes.add(new Episode(12, 4, "Annette seeks a way to reclaim the souls lost to the machine.", "Shadow of the Forge", LocalTime.of(0, 31), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e4.mp4"));
                    cnS2Episodes.add(new Episode(13, 5, "The Vampire Messiah's influence spreads across all of Europe.", "The Black Sun", LocalTime.of(0, 28), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e5.mp4"));
                    cnS2Episodes.add(new Episode(14, 6, "A desperate infiltration mission into the heart of the castle.", "Vampire Killer", LocalTime.of(0, 30), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e6.mp4"));
                    cnS2Episodes.add(new Episode(15, 7, "The revolution and the supernatural war collide in the streets.", "Blood of the Covenant", LocalTime.of(0, 33), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e7.mp4"));
                    cnS2Episodes.add(new Episode(16, 8, "The final clash with Erzsebet determines the fate of the world.", "A New Dawn", LocalTime.of(0, 45), "C:\\Users\\bouss\\Desktop\\netflix\\cn_s2_e8.mp4"));

                    cnSaisons.put(cnS2, cnS2Episodes);
                    series = List.of(
                    		new Serie(1,
                                    "A high school chemistry teacher turned crystal meth producer.",
                                    List.of(Categorie.POLICIER, Categorie.DRAME),
                                    "Breaking Bad", LocalDate.of(2008, 1, 20),
                                    List.of(new Artiste(7, "Bryan Cranston")),
                                    List.of(new Artiste(8, "Vince Gilligan")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\bb.jpg",
                                    bbSaisons),
                                
                                new Serie(2,
                                    "Ninety-seven years after a nuclear war, 100 juveniles are sent back to Earth.",
                                    List.of(Categorie.SCIENCE_FICTION, Categorie.AVENTURE),
                                    "The 100", LocalDate.of(2014, 3, 19),
                                    List.of(new Artiste(9, "Eliza Taylor")),
                                    List.of(new Artiste(10, "Jason Rothenberg")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\the100.jpg",
                                    new HashMap<>()),

                                new Serie(3,
                                    "A woman's search for her soulmate leads her to a dangerous trap.",
                                    List.of(Categorie.DRAME, Categorie.POLICIER),
                                    "Fake Profile", LocalDate.of(2023, 5, 31),
                                    List.of(new Artiste(45, "Carolina Tapan")),
                                    List.of(new Artiste(46, "Pablo Guzmán")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\fake_profile.jpg",
                                    fpSaisons),

                                new Serie(4,
                                    "A woman who has forgotten everything and a man who remembers everything.",
                                    List.of(Categorie.ROMANCE, Categorie.DRAME),
                                    "What Comes After Love", LocalDate.of(2024, 9, 27),
                                    List.of(new Artiste(47, "Lee Se-young"), new Artiste(48, "Sakaguchi Kentaro")),
                                    List.of(new Artiste(49, "Moon Hyun-sung")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\what_comes_after_love.jpg",
                                    wcalSaisons),

                                new Serie(5,
                                    "A gothic horror animation following Richter Belmont.",
                                    List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.ANIME),
                                    "Castlevania: Nocturne", LocalDate.of(2023, 9, 28),
                                    List.of(new Artiste(50, "Richter Belmont"), new Artiste(51, "Alucard")),
                                    List.of(new Artiste(52, "Kevin Bradley")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\castlevania_nocturne.jpg",
                                    cnSaisons),
                                
                                new Serie(6,
                                    "Eight close-knit siblings of the powerful Bridgerton family attempt to find love and happiness in London high society.",
                                    List.of(Categorie.DRAME, Categorie.ROMANCE),
                                    "Bridgerton",
                                    LocalDate.of(2020, 12, 25),
                                    List.of(new Artiste(219, "Adjoa Andoh"), new Artiste(220, "Julie Andrews"), new Artiste(221, "Phoebe Dynevor")),
                                    List.of(new Artiste(222, "Chris Van Dusen")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\bridgerton.jpg",
                                    new HashMap<>()),

                                new Serie(7,
                                    "A dry-witted woman, known only as Fleabag, navigates life and love in London while trying to cope with tragedy.",
                                    List.of(Categorie.COMEDIE, Categorie.DRAME),
                                    "Fleabag",
                                    LocalDate.of(2016, 7, 21),
                                    List.of(new Artiste(223, "Phoebe Waller-Bridge"), new Artiste(224, "Sian Clifford"), new Artiste(225, "Andrew Scott")),
                                    List.of(new Artiste(223, "Phoebe Waller-Bridge")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\fleabag.jpg",
                                    new HashMap<>()),

                                new Serie(8,
                                    "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
                                    List.of(Categorie.DRAME, Categorie.ACTION, Categorie.AVENTURE),
                                    "Game of Thrones",
                                    LocalDate.of(2011, 4, 17),
                                    List.of(new Artiste(226, "Emilia Clarke"), new Artiste(227, "Kit Harington"), new Artiste(228, "Peter Dinklage")),
                                    List.of(new Artiste(229, "David Benioff"), new Artiste(230, "D.B. Weiss")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\game_of_thrones.jpeg",
                                    new HashMap<>()),

                                new Serie(9,
                                    "A peek into the lives of the exploits and privileged lives of the Kardashian-Jenner blended family.",
                                    List.of(Categorie.REAL_TV),
                                    "Keeping Up with the Kardashians",
                                    LocalDate.of(2007, 10, 14),
                                    List.of(new Artiste(231, "Kim Kardashian"), new Artiste(232, "Kris Jenner"), new Artiste(233, "Khloé Kardashian")),
                                    List.of(new Artiste(234, "Ryan Seacrest")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\kuwtk.jpeg",
                                    new HashMap<>()),

                                new Serie(10,
                                    "Stranded on a deserted island, young and flirtatious singles must find their perfect match to escape to 'Paradise' for a night of luxury.",
                                    List.of(Categorie.REAL_TV, Categorie.ROMANCE),
                                    "Single's Inferno",
                                    LocalDate.of(2021, 12, 18),
                                    List.of(new Artiste(235, "Lee Da-hee"), new Artiste(236, "Kyuhyun"), new Artiste(237, "Hong Jin-kyung")),
                                    List.of(new Artiste(238, "Kim Jae-won")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\singles_inferno.jpg",
                                    new HashMap<>()),

                                new Serie(11,
                                    "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
                                    List.of(Categorie.DRAME, Categorie.POLICIER),
                                    "Peaky Blinders",
                                    LocalDate.of(2013, 9, 12),
                                    List.of(new Artiste(239, "Cillian Murphy"), new Artiste(240, "Paul Anderson"), new Artiste(241, "Helen McCrory")),
                                    List.of(new Artiste(242, "Steven Knight")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\peaky_blinders.jpg",
                                    new HashMap<>()),

                                new Serie(12,
                                    "A young boy known as the Avatar must master the four elemental powers to save a world at war with the ruthless Fire Nation.",
                                    List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.ANIMATION),
                                    "Avatar: The Last Airbender",
                                    LocalDate.of(2005, 2, 21),
                                    List.of(new Artiste(243, "Zach Tyler Eisen"), new Artiste(244, "Mae Whitman"), new Artiste(245, "Jack De Sena")),
                                    List.of(new Artiste(246, "Michael Dante DiMartino"), new Artiste(247, "Bryan Konietzko")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\avatar_the_last_airbender.jpg",
                                    new HashMap<>()),

                                new Serie(13,
                                    "Avatar Korra, a headstrong young woman from the Southern Water Tribe, must master the elements and face political and spiritual unrest in the modernizing Republic City.",
                                    List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.ANIMATION),
                                    "The Legend of Korra",
                                    LocalDate.of(2012, 4, 14),
                                    List.of(new Artiste(248, "Janet Varney"), new Artiste(249, "J.K. Simmons"), new Artiste(250, "David Faustino")),
                                    List.of(new Artiste(246, "Michael Dante DiMartino"), new Artiste(247, "Bryan Konietzko")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\legend_of_korra.jpg",
                                    new HashMap<>()),

                                new Serie(14,
                                    "After inheriting sub-atomic powers from his father, the most powerful superhero on the planet, Mark Grayson discovers that his father's legacy may not be as heroic as it seems.",
                                    List.of(Categorie.ANIMATION, Categorie.ACTION, Categorie.AVENTURE),
                                    "Invincible",
                                    LocalDate.of(2021, 3, 25),
                                    List.of(new Artiste(251, "Steven Yeun"), new Artiste(252, "J.K. Simmons"), new Artiste(253, "Sandra Oh")),
                                    List.of(new Artiste(254, "Robert Kirkman")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\invincible.jpg",
                                    new HashMap<>()),

                                new Serie(15,
                                    "An orphaned girl named Riko lives in the Belchero Orphanage in the town of Orth. The town surrounds a strange, giant hole going deep into the earth, which is commonly known as the Abyss.",
                                    List.of(Categorie.ANIME, Categorie.AVENTURE, Categorie.DRAME),
                                    "Made in Abyss",
                                    LocalDate.of(2017, 7, 7),
                                    List.of(new Artiste(255, "Miyu Tomita"), new Artiste(256, "Mariya Ise"), new Artiste(257, "Shiori Izawa")),
                                    List.of(new Artiste(258, "Masayuki Kojima")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\made_in_abyss.jpg",
                                    new HashMap<>()),

                                new Serie(16,
                                    "A middle school girl named Madoka Kaname and her friend Sayaka Miki are offered the chance to have any wish granted by a mysterious creature, provided they become magical girls to fight witches.",
                                    List.of(Categorie.ANIME, Categorie.DRAME, Categorie.THRILLER, Categorie.FANTASY),
                                    "Puella Magi Madoka Magica",
                                    LocalDate.of(2011, 1, 7),
                                    List.of(new Artiste(259, "Aoi Yûki"), new Artiste(260, "Chiwa Saitô"), new Artiste(261, "Eri Kitamura")),
                                    List.of(new Artiste(262, "Akiyuki Shinbô")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\madoka_magica.jpg",
                                    new HashMap<>()),

                                new Serie(17,
                                    "After the hero party vanishes the Demon King, elf mage Frieren and her companions return home. As an elf, Frieren watches her friends age and pass away, leading her to embark on a new journey to understand the hearts of humans.",
                                    List.of(Categorie.ANIME, Categorie.AVENTURE, Categorie.FANTASY),
                                    "Frieren: Beyond Journey's End",
                                    LocalDate.of(2023, 9, 29),
                                    List.of(new Artiste(263, "Atsumi Tanezaki"), new Artiste(264, "Kana Ichinose"), new Artiste(265, "Chiaki Kobayashi")),
                                    List.of(new Artiste(266, "Keiichirô Saitô")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\frieren.jpg",
                                    new HashMap<>()),

                                new Serie(18,
                                    "In a world where premonitions of catastrophe begin to manifest, a group of investigators races against time to uncover the source of an impending global disaster.",
                                    List.of(Categorie.THRILLER, Categorie.DRAME, Categorie.MYSTERE),
                                    "Something Very Bad Is Going To Happen",
                                    LocalDate.of(2025, 10, 31),
                                    List.of(new Artiste(267, "Unknown Lead"), new Artiste(268, "Supporting Cast")),
                                    List.of(new Artiste(269, "Haley Z. Boston")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\something_very_bad.jpeg",
                                    new HashMap<>()),

                                new Serie(19,
                                    "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
                                    List.of(Categorie.DRAME, Categorie.MYSTERE, Categorie.SCIENCE_FICTION),
                                    "Dark",
                                    LocalDate.of(2017, 12, 1),
                                    List.of(new Artiste(270, "Louis Hofmann"), new Artiste(271, "Lisa Vicari"), new Artiste(272, "Maja Schöne")),
                                    List.of(new Artiste(273, "Baran bo Odar"), new Artiste(274, "Jantje Friese")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\dark.jpg",
                                    new HashMap<>()),

                                new Serie(20,
                                    "A beautiful and distinguished family. A private island. A brilliant, damaged girl; a passionate, political boy. A group of four friends—the Liars—whose friendship turns destructive.",
                                    List.of(Categorie.DRAME, Categorie.MYSTERE, Categorie.THRILLER),
                                    "We Were Liars",
                                    LocalDate.of(2025, 6, 12),
                                    List.of(new Artiste(275, "Emily Alyn Lind"), new Artiste(276, "Shay Rudolph"), new Artiste(277, "Joseph Zada")),
                                    List.of(new Artiste(278, "Julie Plec"), new Artiste(279, "Carina Adly MacKenzie")),
                                    "C:\\Users\\bouss\\Desktop\\netflix\\we_were_liars.jpg",
                                    new HashMap<>()),
                                new Serie(21,
                                        "Nanami Momozono is a high school student whose father has run away after being burdened by gambling debts. After saving a mysterious man from a dog, she is gifted his home—a rundown shrine—and becomes the new local Land God.",
                                        List.of(Categorie.ANIME, Categorie.COMEDIE, Categorie.ROMANCE),
                                        "Kamisama Kiss",
                                        LocalDate.of(2012, 10, 1),
                                        List.of(new Artiste(280, "Suzuko Mimori"), new Artiste(281, "Shinnosuke Tachibana"), new Artiste(282, "Daisuke Kishio")),
                                        List.of(new Artiste(283, "Akitarô Daichi")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\kamisama_kiss.jpg",
                                        new HashMap<>()),
                                     new Serie(22,
                                        "Sarah Kim, a woman who has created a false identity based on wealth and social status, sees her world of lies begin to crumble when she becomes a suspect in a murder case.",
                                        List.of(Categorie.DRAME, Categorie.THRILLER, Categorie.POLICIER),
                                        "The Art of Sarah",
                                        LocalDate.of(2026, 2, 13),
                                        List.of(new Artiste(284, "Shin Hye-sun"), new Artiste(285, "Lee Joon-hyuk"), new Artiste(286, "Kim Jae-won")),
                                        List.of(new Artiste(287, "Kim Jin-min")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\the_art_of_sarah.jpg",
                                        new HashMap<>()),
                                     new Serie(23,
                                        "The story of a serial killer, Jeffrey Dahmer, who murdered 17 men and boys between 1978 and 1991, and how he managed to evade arrest for over a decade.",
                                        List.of(Categorie.DRAME, Categorie.POLICIER, Categorie.BIOPIC),
                                        "Dahmer – Monster: The Jeffrey Dahmer Story",
                                        LocalDate.of(2022, 9, 21),
                                        List.of(new Artiste(288, "Evan Peters"), new Artiste(227, "Richard Jenkins"), new Artiste(289, "Niecy Nash")),
                                        List.of(new Artiste(229, "Ryan Murphy"), new Artiste(230, "Ian Brennan")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\dahmer.jpg",
                                        new HashMap<>()),
                                     new Serie(24,
                                        "Two young boxers band together with a benevolent moneylender to take down a ruthless loan shark who preys on the financially desperate.",
                                        List.of(Categorie.ACTION, Categorie.POLICIER),
                                        "Bloodhounds",
                                        LocalDate.of(2023, 6, 9),
                                        List.of(new Artiste(290, "Woo Do-hwan"), new Artiste(291, "Lee Sang-yi"), new Artiste(292, "Huh Joon-ho")),
                                        List.of(new Artiste(293, "Jason Kim")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\bloodhounds.jpg",
                                        new HashMap<>()),
                                     new Serie(25,
                                        "A CODA (child of deaf adult) high school student with a talent for music accidentally travels back in time to 1995, where he forms a band with his younger father and falls in love with a mysterious girl.",
                                        List.of(Categorie.SCIENCE_FICTION, Categorie.COMEDIE, Categorie.ROMANCE),
                                        "Twinkling Watermelon",
                                        LocalDate.of(2023, 9, 25),
                                        List.of(new Artiste(294, "Ryeoun"), new Artiste(295, "Choi Hyun-wook"), new Artiste(296, "Seol In-ah")),
                                        List.of(new Artiste(297, "Son Jong-hyun")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\twinkling_watermelon.jpg",
                                        new HashMap<>()),
                                     new Serie(26,
                                        "Set in a high fantasy world where magic exists but only some can access it, Moiraine, a member of a powerful organization of women, takes five young people on a journey, believing one of them is the reincarnation of the Dragon.",
                                        List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.FANTASY),
                                        "The Wheel of Time",
                                        LocalDate.of(2021, 11, 19),
                                        List.of(new Artiste(298, "Rosamund Pike"), new Artiste(299, "Daniel Henney"), new Artiste(300, "Josha Stradowski")),
                                        List.of(new Artiste(301, "Rafe Judkins")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\wheel_of_time.jpg",
                                        new HashMap<>()),
                                     new Serie(27,
                                        "On her first day at high school, Elena meets Stefan and feels an instant connection. However, she is unaware that Stefan and his brother, Damon, are vampires.",
                                        List.of(Categorie.DRAME, Categorie.ROMANCE, Categorie.MYSTERE, Categorie.FANTASY),
                                        "The Vampire Diaries",
                                        LocalDate.of(2009, 9, 10),
                                        List.of(new Artiste(302, "Nina Dobrev"), new Artiste(303, "Paul Wesley"), new Artiste(304, "Ian Somerhalder")),
                                        List.of(new Artiste(278, "Julie Plec"), new Artiste(305, "Kevin Williamson")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\the_vampire_diaries.jpg",
                                        new HashMap<>()),
                                     new Serie(28,
                                        "An ambitious law professor and five of her students become entwined in a real-life murder plot that will change the entire course of their lives.",
                                        List.of( Categorie.MYSTERE, Categorie.POLICIER),
                                        "How to Get Away with Murder",
                                        LocalDate.of(2014, 9, 25),
                                        List.of(new Artiste(306, "Viola Davis"), new Artiste(307, "Billy Brown"), new Artiste(308, "Jack Falahee")),
                                        List.of(new Artiste(309, "Peter Nowalk"), new Artiste(229, "Ryan Murphy")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\htgawm.jpg",
                                        new HashMap<>()),
                                     new Serie(29,
                                        "A college student navigates life and studies while living in a share house with a beautiful former K-pop idol who has suddenly retired from the limelight.",
                                        List.of(Categorie.MUSICAL, Categorie.ROMANCE, Categorie.COMEDIE),
                                        "Doona!",
                                        LocalDate.of(2023, 10, 20),
                                        List.of(new Artiste(310, "Bae Suzy"), new Artiste(311, "Yang Se-jong"), new Artiste(312, "Park Se-wan")),
                                        List.of(new Artiste(313, "Lee Jung-hyo")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\doona.jpg",
                                        new HashMap<>()),
                                     new Serie(30,
                                        "A shallow model-to-be dies in a sudden accident and is reincarnated in the body of Jane Bingum, a brilliant, thoughtful, and plus-size attorney.",
                                        List.of(Categorie.COMEDIE, Categorie.DRAME, Categorie.FANTASY),
                                        "Drop Dead Diva",
                                        LocalDate.of(2009, 7, 12),
                                        List.of(new Artiste(314, "Brooke Elliott"), new Artiste(315, "Margaret Cho"), new Artiste(316, "Jackson Hurst")),
                                        List.of(new Artiste(317, "Josh Berman")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\drop_dead_diva.jpg",
                                        new HashMap<>()),
                                     new Serie(31,
                                        "Three different but related families face trials and tribulations in their own uniquely comedic ways in this mockumentary-style sitcom.",
                                        List.of(Categorie.COMEDIE, Categorie.DRAME, Categorie.FAMILLE),
                                        "Modern Family",
                                        LocalDate.of(2009, 9, 23),
                                        List.of(new Artiste(318, "Ty Burrell"), new Artiste(319, "Julie Bowen"), new Artiste(320, "Sofia Vergara")),
                                        List.of(new Artiste(321, "Christopher Lloyd"), new Artiste(322, "Steven Levitan")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\modern_family.jpeg",
                                        new HashMap<>()),
                                     new Serie(32,
                                        "In a wacky Rhode Island town, buffoonish Peter Griffin and his dysfunctional family strive to cope with everyday life as they are thrown from one crazy scenario to another.",
                                        List.of(Categorie.ANIMATION, Categorie.COMEDIE),
                                        "Family Guy",
                                        LocalDate.of(1999, 1, 31),
                                        List.of(new Artiste(323, "Seth MacFarlane"), new Artiste(324, "Alex Borstein"), new Artiste(325, "Seth Green")),
                                        List.of(new Artiste(323, "Seth MacFarlane"), new Artiste(326, "David Zuckerman")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\family_guy.jpeg",
                                        new HashMap<>()),
                                     new Serie(33,
                                        "A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is fascinated by.",
                                        List.of(Categorie.THRILLER, Categorie.POLICIER),
                                        "You",
                                        LocalDate.of(2018, 9, 9),
                                        List.of(new Artiste(327, "Penn Badgley"), new Artiste(328, "Victoria Pedretti"), new Artiste(329, "Elizabeth Lail")),
                                        List.of(new Artiste(330, "Greg Berlanti"), new Artiste(331, "Sera Gamble")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\you.jpg",
                                        new HashMap<>()),
                                     new Serie(34,
                                        "Ragnar Lothbrok, a legendary Norse hero and simple farmer, rises to power by raiding England and eventually becomes a Scandinavian King with the support of his family and fellow warriors.",
                                        List.of(Categorie.ACTION, Categorie.AVENTURE, Categorie.DRAME),
                                        "Vikings",
                                        LocalDate.of(2013, 3, 3),
                                        List.of(new Artiste(332, "Travis Fimmel"), new Artiste(333, "Katheryn Winnick"), new Artiste(334, "Clive Standen")),
                                        List.of(new Artiste(335, "Michael Hirst")),
                                        "C:\\Users\\bouss\\Desktop\\netflix\\vikings.jpeg",
                                        new HashMap<>())
                                 );
                             }

                 public static List<Film> getMovies() { return movies; }
                 public static List<Serie> getSeries() { return series; }
             }